trigger:
- main

variables:
  azureWebAppName: 'visionly'

stages:
- stage: Build_and_Deploy_Backend
  jobs:
  - job: Deploy_Azure
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        npm install
        npm run build --if-present
      displayName: 'Install and Build Backend'
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'MyAzureConnection'
        appName: $(azureWebAppName)
        package: '$(System.DefaultWorkingDirectory)'

- stage: Build_Android
  dependsOn: Build_and_Deploy_Backend 
  jobs:
  - job: Build_APK_AAB
    pool:
      vmImage: 'ubuntu-latest' 
    variables:
    - group: visionly-secrets # Pastikan nama ini sama dengan di menu Library
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    
    - script: npm install
      displayName: 'Install Dependencies'

    # Membuat file .env untuk API Key Gemini
    - script: |
        echo "GEMINI_API_KEY=$(GEMINI_API_KEY)" > .env
      displayName: 'Inject Gemini API Key'

    - script: |
        cd android
        chmod +x gradlew
        ./gradlew bundleRelease assembleRelease 
      displayName: 'Build Android (AAB & APK)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'android/app/build/outputs/bundle/release'
        ArtifactName: 'Android-App-Bundle'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'android/app/build/outputs/apk/release'
        ArtifactName: 'Android-APK-Installable'
        publishLocation: 'Container'